# Generated by Django 5.0.3 on 2024-04-17 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
    ]
